// <auto-generated />
using System;
using Blog.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Persistence.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250728061156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Domain.Entities.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb21c477-f44b-4b4d-8309-c46eb88a8e5e"),
                            Author = "Author 1",
                            Content = "This is the content for post 1.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 1",
                            Title = "Seed Post 1"
                        },
                        new
                        {
                            Id = new Guid("1e2ebd66-7ef8-4898-990d-cab47e92b070"),
                            Author = "Author 2",
                            Content = "This is the content for post 2.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 2",
                            Title = "Seed Post 2"
                        },
                        new
                        {
                            Id = new Guid("d31ad2dd-6bd8-40cf-a105-6bb2837f2262"),
                            Author = "Author 3",
                            Content = "This is the content for post 3.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 2, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 3",
                            Title = "Seed Post 3"
                        },
                        new
                        {
                            Id = new Guid("f6c9785d-19f0-4dba-9070-200173ba21a5"),
                            Author = "Author 4",
                            Content = "This is the content for post 4.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 3, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 4",
                            Title = "Seed Post 4"
                        },
                        new
                        {
                            Id = new Guid("36d0139d-0163-492a-823f-74dc5aebcbe3"),
                            Author = "Author 5",
                            Content = "This is the content for post 5.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 4, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 5",
                            Title = "Seed Post 5"
                        },
                        new
                        {
                            Id = new Guid("077e988e-61d1-49e4-bf5f-0a182dfa05db"),
                            Author = "Author 6",
                            Content = "This is the content for post 6.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 6",
                            Title = "Seed Post 6"
                        },
                        new
                        {
                            Id = new Guid("f8ff5e9d-a55b-4595-8d50-b4292cbfc6ce"),
                            Author = "Author 7",
                            Content = "This is the content for post 7.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 6, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 7",
                            Title = "Seed Post 7"
                        },
                        new
                        {
                            Id = new Guid("c7d08df2-3835-45ec-8e10-7952543e4f35"),
                            Author = "Author 8",
                            Content = "This is the content for post 8.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 7, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 8",
                            Title = "Seed Post 8"
                        },
                        new
                        {
                            Id = new Guid("0ff63aa1-a57f-4df6-99b4-5902229bdfdf"),
                            Author = "Author 9",
                            Content = "This is the content for post 9.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 8, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 9",
                            Title = "Seed Post 9"
                        },
                        new
                        {
                            Id = new Guid("01bf6d3d-1a41-43ff-972c-7adc925fbca7"),
                            Author = "Author 10",
                            Content = "This is the content for post 10.",
                            CreatedAt = new DateTime(2025, 7, 28, 6, 9, 0, 0, DateTimeKind.Utc),
                            Description = "Description for post 10",
                            Title = "Seed Post 10"
                        });
                });

            modelBuilder.Entity("Blog.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("eb21c477-f44b-4b4d-8309-c46eb88a8e5e"),
                            Content = "Comment 1 for post 1",
                            PostedAt = new DateTime(2025, 7, 28, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("01020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("eb21c477-f44b-4b4d-8309-c46eb88a8e5e"),
                            Content = "Comment 2 for post 1",
                            PostedAt = new DateTime(2025, 7, 28, 6, 1, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("01030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("eb21c477-f44b-4b4d-8309-c46eb88a8e5e"),
                            Content = "Comment 3 for post 1",
                            PostedAt = new DateTime(2025, 7, 28, 6, 2, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("02010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("1e2ebd66-7ef8-4898-990d-cab47e92b070"),
                            Content = "Comment 1 for post 2",
                            PostedAt = new DateTime(2025, 7, 28, 6, 3, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("02020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("1e2ebd66-7ef8-4898-990d-cab47e92b070"),
                            Content = "Comment 2 for post 2",
                            PostedAt = new DateTime(2025, 7, 28, 6, 4, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("02030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("1e2ebd66-7ef8-4898-990d-cab47e92b070"),
                            Content = "Comment 3 for post 2",
                            PostedAt = new DateTime(2025, 7, 28, 6, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("03010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("d31ad2dd-6bd8-40cf-a105-6bb2837f2262"),
                            Content = "Comment 1 for post 3",
                            PostedAt = new DateTime(2025, 7, 28, 6, 6, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("03020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("d31ad2dd-6bd8-40cf-a105-6bb2837f2262"),
                            Content = "Comment 2 for post 3",
                            PostedAt = new DateTime(2025, 7, 28, 6, 7, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("03030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("d31ad2dd-6bd8-40cf-a105-6bb2837f2262"),
                            Content = "Comment 3 for post 3",
                            PostedAt = new DateTime(2025, 7, 28, 6, 8, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("04010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("f6c9785d-19f0-4dba-9070-200173ba21a5"),
                            Content = "Comment 1 for post 4",
                            PostedAt = new DateTime(2025, 7, 28, 6, 9, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("04020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("f6c9785d-19f0-4dba-9070-200173ba21a5"),
                            Content = "Comment 2 for post 4",
                            PostedAt = new DateTime(2025, 7, 28, 6, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("04030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("f6c9785d-19f0-4dba-9070-200173ba21a5"),
                            Content = "Comment 3 for post 4",
                            PostedAt = new DateTime(2025, 7, 28, 6, 11, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("05010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("36d0139d-0163-492a-823f-74dc5aebcbe3"),
                            Content = "Comment 1 for post 5",
                            PostedAt = new DateTime(2025, 7, 28, 6, 12, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("05020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("36d0139d-0163-492a-823f-74dc5aebcbe3"),
                            Content = "Comment 2 for post 5",
                            PostedAt = new DateTime(2025, 7, 28, 6, 13, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("05030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("36d0139d-0163-492a-823f-74dc5aebcbe3"),
                            Content = "Comment 3 for post 5",
                            PostedAt = new DateTime(2025, 7, 28, 6, 14, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("06010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("077e988e-61d1-49e4-bf5f-0a182dfa05db"),
                            Content = "Comment 1 for post 6",
                            PostedAt = new DateTime(2025, 7, 28, 6, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("06020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("077e988e-61d1-49e4-bf5f-0a182dfa05db"),
                            Content = "Comment 2 for post 6",
                            PostedAt = new DateTime(2025, 7, 28, 6, 16, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("06030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("077e988e-61d1-49e4-bf5f-0a182dfa05db"),
                            Content = "Comment 3 for post 6",
                            PostedAt = new DateTime(2025, 7, 28, 6, 17, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("07010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("f8ff5e9d-a55b-4595-8d50-b4292cbfc6ce"),
                            Content = "Comment 1 for post 7",
                            PostedAt = new DateTime(2025, 7, 28, 6, 18, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("07020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("f8ff5e9d-a55b-4595-8d50-b4292cbfc6ce"),
                            Content = "Comment 2 for post 7",
                            PostedAt = new DateTime(2025, 7, 28, 6, 19, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("07030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("f8ff5e9d-a55b-4595-8d50-b4292cbfc6ce"),
                            Content = "Comment 3 for post 7",
                            PostedAt = new DateTime(2025, 7, 28, 6, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("08010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("c7d08df2-3835-45ec-8e10-7952543e4f35"),
                            Content = "Comment 1 for post 8",
                            PostedAt = new DateTime(2025, 7, 28, 6, 21, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("08020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("c7d08df2-3835-45ec-8e10-7952543e4f35"),
                            Content = "Comment 2 for post 8",
                            PostedAt = new DateTime(2025, 7, 28, 6, 22, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("08030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("c7d08df2-3835-45ec-8e10-7952543e4f35"),
                            Content = "Comment 3 for post 8",
                            PostedAt = new DateTime(2025, 7, 28, 6, 23, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("09010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("0ff63aa1-a57f-4df6-99b4-5902229bdfdf"),
                            Content = "Comment 1 for post 9",
                            PostedAt = new DateTime(2025, 7, 28, 6, 24, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("09020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("0ff63aa1-a57f-4df6-99b4-5902229bdfdf"),
                            Content = "Comment 2 for post 9",
                            PostedAt = new DateTime(2025, 7, 28, 6, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("09030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("0ff63aa1-a57f-4df6-99b4-5902229bdfdf"),
                            Content = "Comment 3 for post 9",
                            PostedAt = new DateTime(2025, 7, 28, 6, 26, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10010000-0000-0000-0000-000000000000"),
                            Author = "Commenter 1",
                            BlogPostId = new Guid("01bf6d3d-1a41-43ff-972c-7adc925fbca7"),
                            Content = "Comment 1 for post 10",
                            PostedAt = new DateTime(2025, 7, 28, 6, 27, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10020000-0000-0000-0000-000000000000"),
                            Author = "Commenter 2",
                            BlogPostId = new Guid("01bf6d3d-1a41-43ff-972c-7adc925fbca7"),
                            Content = "Comment 2 for post 10",
                            PostedAt = new DateTime(2025, 7, 28, 6, 28, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10030000-0000-0000-0000-000000000000"),
                            Author = "Commenter 3",
                            BlogPostId = new Guid("01bf6d3d-1a41-43ff-972c-7adc925fbca7"),
                            Content = "Comment 3 for post 10",
                            PostedAt = new DateTime(2025, 7, 28, 6, 29, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Blog.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Blog.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("Blog.Domain.Entities.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
